### ISSUE TITLE
Subpage navigation issue

### ISSUE THREAD

**Issue by Schotsl** [ElectroGamez/wouterdebruijn.nl#3]
When I go to a subpage on the website, for instance [this](https://wouterdebruijn.nl/sjors.html) page (this also happens to be my favorite page). I still see the same navigation bar (About, Projects, Rights) even though none of these 3 options are on the page and If I click them nothing happens? :(

**Comment by wouterdebruijn** [comment]
Thank you for reporting this issue. I am actually working on a full rewrite, so this issue will be fixed in the new version.

**Comment by Schotsl** [comment]
I would add the[ pull request](https://github.com/ElectroGamez/wouterdebruijn.nl/pull/5) but I'm not allowed to :(

“The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.”
